### ISSUE TITLE
gagal login

### ISSUE THREAD

**Issue by SatyaRac** [rakaadinugroho/Elearning-Mobile#8]
halo mas raka. saya sudah mensamakan konfigurasi IP di API dan sudah dalam satu jaringan . tapi muncul ERROR:HTTP 404 saat run di emulator. Sejauh ini saya sudah coba di postman API nya jalan.

**Comment by rakanugroho** [comment]
halo, apakah kamu sudah mensetting base url API kamu di projek androidnya?. cek disini ya https://github.com/rakaadinugroho/Elearning-Mobile/blob/master/app/src/main/java/com/rakaadinugroho/msuryanusatara/core/Const.java

**Comment by SatyaRac** [comment]
> halo, apakah kamu sudah mensetting base url API kamu di projek androidnya?. cek disini ya https://github.com/rakaadinugroho/Elearning-Mobile/blob/master/app/src/main/java/com/rakaadinugroho/msuryanusatara/core/Const.java

sudah mas `public final class BuildConfig {
  public static final boolean DEBUG = Boolean.parseBoolean("true");
  public static final String APPLICATION_ID = "com.rakaadinugroho.msuryanusatara";
  public static final String BUILD_TYPE = "debug";
  public static final String FLAVOR = "";
  public static final int VERSION_CODE = 1;
  public static final String VERSION_NAME = "1.0";
  // Fields from default config.
  public static final String BASE_URL = "http://192.168.xxx.x/Elearning-Mobile-API/";
}`

**Comment by rakaadinugroho** [comment]
HTTP response 404 berarti endpointnya tidak tersedia, jika di settingan web servicenya kamu tidak menggunakan `.htaccess` maka bisa menambahkan base urlnya menjadi `BASE_URL = "http://192.168.xxx.x/Elearning-Mobile-API/index.php"`

**Comment by SatyaRac** [comment]
muncul error IllegalArgumentException mas

**Comment by rakaadinugroho** [comment]
mungkin kurang `/` dibelakangnya baseURL. coba baca lognya kembali

**Comment by SatyaRac** [comment]
solved mas. di `base.url http://192.168.xxx.x/Elearning-Mobile-API/` 
dikasih `/` tapi di inteface `RequestApi`  `/` dihapus. terimakasih mas
