### ISSUE TITLE
ERROR HTTP 404

### ISSUE THREAD

**Issue by andreanoscar** [rakaadinugroho/Elearning-Mobile#9]
mas, saya sudah coba clone projek mas, cuma sewaktu saya setting base url error http 404, saya sudah coba hosting, local ttep ga bisa mas

**Comment by rakanugroho** [comment]
base url dan enpointnya sudah kamu coba test terlebih dahulu di http client semisal postman?.

**Comment by andreanoscar** [comment]
sudah di test mas hasilnya unauthorised untuk Category dan unknown method untuk post
